import Link from 'next/link'
import './globals.css'
import { Manrope } from 'next/font/google'
import Header from '@/components/header'
import Footer from '@/components/footer'
import Lenis from '@/components/Lenis'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Lenis>
        <body
          className={`antialiased min-h-screen bg-white text-slate-900  ${manrope.className}`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </Lenis>
    </html>
  )
}
